name: Check Ollama Servers

on:
  schedule:
    - cron: '0 0 */4 * *'  # 每4天运行一次
  workflow_dispatch:  # 允许手动触发

# 添加并发控制，使用与update-servers相同的组
concurrency:
  group: ollama-server-management
  cancel-in-progress: false  # 设置为false会等待其他工作流完成

jobs:
  check-servers:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的Git历史记录
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas
          
      - name: Check servers availability
        run: python .github/scripts/check_servers.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --rebase  # 先拉取最新更改并变基
          git add output_with_models.csv
          git commit -m "Update server list: remove inactive servers" || exit 0
          git push 