name: Check Ollama Servers

on:
  schedule:
    - cron: '0 0 */4 * *'  # 每4天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-servers:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的git历史
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas
          
      - name: Check servers availability
        run: python .github/scripts/check_servers.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git stash -u  # 暂存所有更改，包括未跟踪的文件
          git pull --rebase  # 拉取最新更改
          git stash pop  # 恢复暂存的更改
          git add output_with_models.csv
          git commit -m "Update server list: remove inactive servers" || exit 0
          git push 